String? fullName;
String? eiDNumber;
String? nationality;
String? nationalityCode;
String? expiryDate;
String? dob;
String? gender;
String? photo;
String? docPhoto;
String? passportNumber;
double photoMatchScore = 0;
