name: dialup_mobile_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_sizer: ^1.0.5
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/icons/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYREGULAR.OTF
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYMEDIUM.OTF
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYBOLD.OTF
          weight: 700
    - family: Heiti TC Light
      fonts:
        - asset: assets/fonts/HeitiTC/heiti-tc-light.ttf
          weight: 300
