name: dialup_mobile_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  # bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_sizer: ^1.0.5
  flutter_svg: ^2.0.4
  pinput: ^2.2.31

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/icons/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYREGULAR.OTF
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYMEDIUM.OTF
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYBOLD.OTF
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.woff
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Italic.woff
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.woff
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.woff
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Semibold.woff
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.woff
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Extrabold.woff
          weight: 700
