name: dialup_mobile_app
description: Digital Banking Application for Dhabi

publish_to: "none"

version: 1.0.0+28

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cached_memory_image: ^1.3.1
  camera: ^0.10.4
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.2.0
  dropdown_button2: ^2.0.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_core: ^2.12.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_appauth: ^4.2.1+1
  flutter_bloc: ^8.1.2
  flutter_document_reader_api: ^6.7.3
  flutter_document_reader_core_fullrfid: ^6.7.0
  flutter_dotenv: ^5.0.2
  flutter_face_api: ^5.1.3
  flutter_face_core: ^5.1.0
  flutter_holo_date_picker: ^1.1.0
  flutter_image_compress: ^2.0.3
  flutter_secure_storage: ^8.0.0
  flutter_sizer: ^1.0.5
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.4
  flutter_switch: ^0.3.2
  flutter_widget_from_html: ^0.10.0
  http: ^0.13.5
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  local_auth: ^2.1.6
  open_file: ^3.3.1
  open_settings: ^2.0.2
  package_info_plus: ^3.1.0
  path_provider: ^2.0.15
  pinput: ^2.2.31
  platform_device_id: ^1.0.1
  shared_preferences: ^2.1.1
  shimmer: ^2.0.0
  simple_tooltip: ^1.2.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  rename: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/images/banners/
    - assets/regula.license
    - .env
    - .env.production
    - .env.development
    - .env.staging

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYREGULAR.OTF
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYMEDIUM.OTF
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFPRODISPLAYBOLD.OTF
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.woff
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Italic.woff
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.woff
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.woff
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Semibold.woff
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.woff
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Extrabold.woff
          weight: 700
