// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr6dGmXu6raUsq9Lq4kZZkt-vS1mSAdAo',
    appId: '1:1058943174980:web:bb250b27b8aec82f472f11',
    messagingSenderId: '1058943174980',
    projectId: 'dabi-a4f76',
    authDomain: 'dabi-a4f76.firebaseapp.com',
    storageBucket: 'dabi-a4f76.appspot.com',
    measurementId: 'G-R2HNQHQ7M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLIEUJE7YwrIrnUCyAAJv65uVYUw0NN6c',
    appId: '1:1058943174980:android:e681f9f94ae38022472f11',
    messagingSenderId: '1058943174980',
    projectId: 'dabi-a4f76',
    storageBucket: 'dabi-a4f76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCniUTvLrIwnmPjETkcn-omUwrOekRAaeA',
    appId: '1:1058943174980:ios:243da01466faec63472f11',
    messagingSenderId: '1058943174980',
    projectId: 'dabi-a4f76',
    storageBucket: 'dabi-a4f76.appspot.com',
    iosClientId: '1058943174980-r7eke3v9iiidlpkbu0o1baomillefg63.apps.googleusercontent.com',
    iosBundleId: 'com.fh.Dabi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCniUTvLrIwnmPjETkcn-omUwrOekRAaeA',
    appId: '1:1058943174980:ios:243da01466faec63472f11',
    messagingSenderId: '1058943174980',
    projectId: 'dabi-a4f76',
    storageBucket: 'dabi-a4f76.appspot.com',
    iosClientId: '1058943174980-r7eke3v9iiidlpkbu0o1baomillefg63.apps.googleusercontent.com',
    iosBundleId: 'com.fh.Dabi',
  );
}
